# Generated by Django 5.1.4 on 2026-08-06 14:19

import django_ckeditor_5.fields
from django.db import migrations, models

# Panel modellari managed=False — CreateModel faqat Django "holatini" to'ldiradi,
# jadval YARATMAYDI (users/reminders/referrals'ni bot yaratadi). 'broadcasts' esa
# YANGI jadval: adminka yozadi, bot o'qiydi — shu sabab uni jismonan shu yerda
# RunSQL bilan yaratamiz. IF NOT EXISTS — bot avval yaratgan bo'lsa xatosiz o'tadi.
_CREATE_BROADCASTS = """
CREATE TABLE IF NOT EXISTS broadcasts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    text TEXT NOT NULL,
    target TEXT NOT NULL DEFAULT 'all',
    target_value TEXT,
    status TEXT NOT NULL DEFAULT 'pending',
    total INTEGER NOT NULL DEFAULT 0,
    sent INTEGER NOT NULL DEFAULT 0,
    failed INTEGER NOT NULL DEFAULT 0,
    error TEXT,
    created_at TEXT,
    sent_at TEXT
);
"""


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('name', models.TextField(blank=True, null=True, verbose_name='Ismi')),
                ('last_name', models.TextField(blank=True, null=True, verbose_name='Familiya')),
                ('username', models.TextField(blank=True, null=True, verbose_name='TG username')),
                ('phone', models.TextField(blank=True, null=True, verbose_name='Telefon')),
                ('language_code', models.TextField(blank=True, null=True, verbose_name='Til')),
                ('is_premium', models.BooleanField(blank=True, null=True, verbose_name='Premium')),
                ('registered', models.BooleanField(default=False, verbose_name="Ro'yxatdan o'tgan")),
                ('digest_enabled', models.BooleanField(default=True, verbose_name='Digest yoqilgan')),
                ('digest_hour', models.IntegerField(default=7, verbose_name='Digest soati')),
                ('digest_minute', models.IntegerField(default=0, verbose_name='Digest daqiqasi')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Kelgan vaqti')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Oxirgi faollik')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Xabar matni')),
                ('target', models.TextField(choices=[('all', '📢 Hammaga (barcha foydalanuvchilar)'), ('username', "👤 Bitta userga — username bo'yicha"), ('phone', "📱 Bitta userga — telefon bo'yicha")], default='all', verbose_name='Kimga')),
                ('target_value', models.TextField(blank=True, help_text="Faqat 'username' yoki 'telefon' tanlaganda to'ldiring. Masalan: @ali yoki +998901234567", null=True, verbose_name='Username yoki Telefon')),
                ('status', models.TextField(choices=[('pending', '⏳ Navbatda'), ('sending', '📤 Yuborilmoqda'), ('done', '✅ Yuborildi'), ('error', '❌ Xato')], default='pending', verbose_name='Holat')),
                ('total', models.IntegerField(default=0, verbose_name='Jami qabul qiluvchi')),
                ('sent', models.IntegerField(default=0, verbose_name='Yuborildi')),
                ('failed', models.IntegerField(default=0, verbose_name='Yetib bormadi')),
                ('error', models.TextField(blank=True, null=True, verbose_name='Xato izohi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan vaqti')),
            ],
            options={
                'verbose_name': 'Xabar yuborish',
                'verbose_name_plural': '📢 Xabar yuborish',
                'db_table': 'broadcasts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Havola tokeni')),
                ('text', models.TextField(verbose_name='Eslatma matni')),
                ('freq', models.TextField(choices=[('once', '📌 Bir marta'), ('daily', '📅 Har kuni'), ('every2', '🔁 Kun ora'), ('weekly', '📆 Haftada bir'), ('monthly', '🗓 Oyda bir')], verbose_name='Takrorlanish')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], null=True, verbose_name='Hafta kuni')),
                ('monthday', models.IntegerField(blank=True, null=True, verbose_name='Oy kuni')),
                ('hour', models.IntegerField(verbose_name='Soat')),
                ('minute', models.IntegerField(verbose_name='Daqiqa')),
                ('start_date', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan')),
                ('claimed_count', models.IntegerField(default=0, verbose_name='Qabul soni')),
            ],
            options={
                'verbose_name': 'Referal',
                'verbose_name_plural': 'Referallar',
                'db_table': 'referrals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Eslatma matni')),
                ('freq', models.TextField(choices=[('once', '📌 Bir marta'), ('daily', '📅 Har kuni'), ('every2', '🔁 Kun ora'), ('weekly', '📆 Haftada bir'), ('monthly', '🗓 Oyda bir')], verbose_name='Takrorlanish')),
                ('weekday', models.IntegerField(blank=True, choices=[(0, 'Dushanba'), (1, 'Seshanba'), (2, 'Chorshanba'), (3, 'Payshanba'), (4, 'Juma'), (5, 'Shanba'), (6, 'Yakshanba')], null=True, verbose_name='Hafta kuni')),
                ('monthday', models.IntegerField(blank=True, null=True, verbose_name='Oy kuni')),
                ('hour', models.IntegerField(verbose_name='Soat')),
                ('minute', models.IntegerField(verbose_name='Daqiqa')),
                ('start_date', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(blank=True, null=True, verbose_name='Yaratilgan')),
            ],
            options={
                'verbose_name': 'Eslatma',
                'verbose_name_plural': 'Eslatmalar',
                'db_table': 'reminders',
                'managed': False,
            },
        ),
        # 'broadcasts' jadvalini jismonan yaratamiz (reverse — noop: o'chirmaymiz)
        migrations.RunSQL(_CREATE_BROADCASTS, reverse_sql=migrations.RunSQL.noop),
    ]
